name: 'Update Bot'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '10 10 * * *'  # 每天 10:10 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
        
      - name: 'Set up Python'
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: 'Install dependencies'
        run: pip install requests
          
      - name: 'Run Update Script'
        run: python3 ./update.py
        
      - name: 'Commit Changes'
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config --global user.email "30486766+entr0pia@users.noreply.github.com"
          git config --global user.name "entr0pia"
          git add .
          git commit -m "update by bot [skip ci]"
          
      - name: 'Push Changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
